### ISSUE TITLE
Update examples CI configuration

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-examples#6]
The CI configuration for this repository was originally written for Bitbucket Pipelines and should be migrated to CircleCI.

Steps:
- [ ] Set up generic CI config copied from `signac` repo: https://github.com/glotzerlab/signac/blob/master/.circleci/config.yml
- [ ] Remove `signac-utils`, which doesn't exist anymore
- [ ] Remove `glotzer` conda channel (everything is on `conda-forge` now)
- [ ] Add missing package dependencies
- [ ] Use Python 3.8 instead of 3.6
- [ ] Ensure tests are being run for all the examples
- [ ] Remove Bitbucket Pipelines file

**Comment by mikemhenry** [comment]
Using `nbval` via `pytest` with `python -m pytest -v --nbval --nbval-lax` would be a good idea as well.

**Comment by kidrahahjo** [comment]
Hello
Can you assign me this one?

**Comment by CryoZEUS** [comment]
I'd love to work on this issue, @bdice

**Comment by CryoZEUS** [comment]
While writing the **config.yml** file for `signac-examples` to setup CI configuration, the jobs that need to be run include the python3 and python versions from 3.5 to 3.8 right? Or is it just 3.8? Also, is deployment and testing of `pypi` required (`test-deploy-pypi` and `deploy-pypi`) , like it is for `signac` repo?

**Comment by bdice** [comment]
@CryoZEUS You can just run Python 3.8 for the examples in this repo. Also there won't be any deployment (`test-deploy-pypi` and `deploy-pypi`) because there aren't any packages in this repository (it's just example codes). You're essentially just copying the syntax template of the `config.yml`, ripping out most of the commands, and then putting back in some commands that are based on the contents of the old `bitbucket-pipelines.yml` file in this repo. Thanks for working on this!

**Comment by bdice** [comment]
@CryoZEUS I just enabled CI for this repo: https://app.circleci.com/pipelines/github/glotzerlab/signac-examples

Do your best with an initial draft, but it may not actually trigger and run the CI until we merge an initial PR that has the file `.circleci/config.yml`. We can make a second PR after that draft is merged to fix any issues.

**Comment by CryoZEUS** [comment]
That clears it up. Thanks, @bdice it's a pleasure. I'll get to it asap and try to finish it asap.

**Comment by CryoZEUS** [comment]
Okay, I'll add a draft of the config.yml file and you can suggest changes as required.

**Comment by CryoZEUS** [comment]
https://github.com/CryoZEUS/signac-examples/commit/ba123dcad5c6f28b342c5a08497ded5cf4cc84d4
@bdice I've added 2 parallel jobs `staging` and `master` in the workflow, which were earlier two branches in the bitbucket-pipelines.yml file here: 
https://github.com/glotzerlab/signac-examples/blob/master/bitbucket-pipelines.yml

Additonally, I've removed `glotzer` conda channel from the config file.

**Comment by kidrahahjo** [comment]
> @CryoZEUS You can just run Python 3.8 for the examples in this repo. Also there won't be any deployment (`test-deploy-pypi` and `deploy-pypi`) because there aren't any packages in this repository (it's just example codes). You're essentially just copying the syntax template of the `config.yml`, ripping out most of the commands, and then putting back in some commands that are based on the contents of the old `bitbucket-pipelines.yml` file in this repo. Thanks for working on this!

@bdice In order to take maintain consistency for the support of the signac framework with the different python versions, shouldn't we run the examples for other versions of Python too?

**Comment by bdice** [comment]
@kidrahahjo @CryoZEUS I would be fine testing the oldest and newest versions, but I expect the CI time to be fairly long for running these. I see that @csadorf agrees with you -- feel free to add other versions and we can assess based on the run time. We have a finite amount of "free CI credits for open-source projects" due to recent changes in CircleCI's policies. While I don't think we're close to running out, I do think that we should be mindful of their resources over the long term.

**Comment by CryoZEUS** [comment]
While trying to execute commands from `config.yml` CI file, there is dependency from `run-tests.sh` file on **`flow-test`** script in **[signac-utils](https://bitbucket.org/glotzer/signac-utils/src/master/)**. As discussed with @vyasr  in #general , we're now supposed to check how many projects in **signac-examples/projects** can be parsed and their tests executed based on the older **flow-test** script. When I try executing it in a docker, it tries to clone the repo when it reads README.md . I tried removing the README file thinking it might start parsing the project README files. But I believe the `flow-test` file needs to be changed in a lot of places maybe? It would be helpful if someone could help me understand how to go about it? @csadorf ?
(I have added the flow-test script in [projects](https://github.com/CryoZEUS/signac-examples/blob/master/projects/flow-test) folder in the last commit of my PR)
Here is the output when I try running `flow-test` with and without README.md:
![issueCI](https://user-images.githubusercontent.com/37624599/78609484-6989b180-7880-11ea-8edf-11d6f128dc27.png)

**Comment by kidrahahjo** [comment]
@bdice should we close this?

**Comment by bdice** [comment]
Yup, this is done. Thanks for noticing @kidrahahjo!
