### ISSUE TITLE
labels do not appear in print_status

### ISSUE THREAD

**Issue by phmalek** [glotzerlab/signac-examples#8]
Following the notebook https://github.com/glotzerlab/signac-examples/blob/master/notebooks/signac-flow_Ideal_Gas_Example.ipynb, labels do not appear when I call print_status

**Comment by csadorf** [comment]
Thank you for reporting!

**Comment by kidrahahjo** [comment]
@csadorf  Can I handle this issue?

**Comment by csadorf** [comment]
> @csadorf Can I handle this issue?

Absolutely!
